theme: jekyll-theme-minimal
title: "Sharon S. Wang"
logo: "Headshot-2018-square.jpeg"

## Contact Info
**Email:** [sharonwang.ssw@gmail.com](mailto:sharonwang.ssw@gmail.com)

**Phone:** \(812\)-390-0296

**Twitter:** [@\_wangsharon](https://twitter.com/\_wangsharon)

